version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/index.html

permissions:
  - object: /var/www/html/index.html
    owner: ec2-user
    group: ec2-user
    mode: 644

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ec2-user

